apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  type: NodePort
  selector:
    app: netology-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
