apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_NAME-dep
  namespace: NAMESPACE
  labels:
    app: APP_NAME
    version: "IMAGE_TAG"
spec:
  replicas: REPLICA_COUNT
  selector:
    matchLabels:
      app: APP_NAME
  template:
    metadata:
      labels:
        app: APP_NAME
        version: "IMAGE_TAG"
    spec:
      containers:
      - name: APP_NAME
        image: nginx:IMAGE_TAG
        ports:
        - containerPort: 80
        env:
        - name: APP_VERSION
          value: "IMAGE_TAG"
