apiVersion: v1
kind: Service
metadata:
  name: APP_NAME-svc
  namespace: NAMESPACE
  labels:
    app: APP_NAME
    version: "IMAGE_TAG"
spec:
  selector:
    app: APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
