apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-init
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup nginx-service.default.svc.cluster.local; do echo waiting for service; sleep 2; done; echo Service is ready!']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
